import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test deploy nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1>Hello NgocHai</h1>
        <div>test update repo with deploy nextjs</div>
        <Image src='https://st.quantrimang.com/photos/image/2021/07/28/trung-thu-1.jpg' width={280} height={280} />
      </main>
    </div>
  )
}
